language: cpp
sudo: required
dist: trusty

before_install:
- sudo apt-get update
- sudo apt-get install -y git gcc-4.8 g++-4.8 autoconf cmake libtool wget unzip libbz2-dev zlib1g-dev
- sudo apt-get install -y python-dev

install:
- sudo sh install_boostpython.sh >> tmp_install_boostpython.txt
- mkdir rocketmqlib
- cd rocketmqlib
- wget https://opensource-rocketmq-client.oss-cn-hangzhou.aliyuncs.com/cpp-client/linux/1.2.0/RHEL7.x/librocketmq.tar.gz
- tar -xzf librocketmq.tar.gz
- sudo cp librocketmq.so librocketmq.a /usr/local/lib/
- sudo cp -r rocketmq /usr/local/include/
- cd ../

before_script:
- export LD_LIBRARY_PATH=/usr/local/lib

script:
- mkdir build && cd build
- cmake ../ -DBoost_USE_STATIC_LIBS=OFF -DROCKETMQ_USE_STATIC_LIBS=OFF
- make
